### ISSUE TITLE
compilation failure

### ISSUE THREAD

**Issue by kazuf3** [sharkdp/vivid#24]
```
==> Making package: vivid 0.4.0-1 (Sun 09 Dec 2018 07:39:44 PM GMT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
   Compiling libc v0.2.44
   Compiling cc v1.0.25
   Compiling unicode-width v0.1.5
   Compiling bitflags v1.0.4
   Compiling strsim v0.7.0
   Compiling vec_map v0.8.1
   Compiling ansi_term v0.11.0
   Compiling linked-hash-map v0.5.1
   Compiling lazy_static v1.2.0
   Compiling yaml-rust v0.4.2
   Compiling term_size v0.3.1
   Compiling atty v0.2.11
   Compiling textwrap v0.10.0
   Compiling ansi_colours v1.0.1
   Compiling clap v2.32.0
   Compiling vivid v0.4.0 (file:///home/kazuhiro/.cache/yay/vivid/src/vivid-0.4.0)
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> src/error.rs:25:29
   |
25 |     fn fmt(&self, fmt: &mut std::fmt::Formatter) -> result::Result<(), std::fmt::Error>
{
   |                             ^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> src/error.rs:25:72
   |
25 |     fn fmt(&self, fmt: &mut std::fmt::Formatter) -> result::Result<(), std::fmt::Error>
{
   |                                                                        ^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> src/error.rs:72:22
   |
72 | pub type Result<T> = std::result::Result<T, VividError>;
   |                      ^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> src/util.rs:17:17
   |
17 |     opt: Option<std::result::Result<T, E>>,
   |                 ^^^

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> src/util.rs:18:6
   |
18 | ) -> std::result::Result<Option<T>, E> {
   |      ^^^

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `vivid`.

To learn more, run the command again with --verbose.
==> ERROR: A failure occurred in build().
    Aborting...
Error making: vivid
```

https://github.com/rust-lang/rust/issues/44660

This happens with both `yay -S vivid` and `cargo install vivid` .

**Comment by polyzen** [comment]
Are you using Rust 1.30.1 from the repos?

**Comment by sharkdp** [comment]
I have recently updated vivid to Rust 2018 (>= Rust 1.31) in 099ff6be8f0f802639618584555c39426bfb59b9 but completely forgot to update the README and .travis.yml (which currently shows a build failure, too), sorry about that. I'll update this soon.

Does having Rust 1.31 as a dependency cause any problems with packaging for Arch?

**Comment by polyzen** [comment]
Turns out our Rust maintainer is currently in the process of building the 1.31 package. \o/

**Comment by sharkdp** [comment]
Ah, great!

If there is any problem, it's also easy to restore 1.30 compatibility.

@kazuf3 The latest vivid release should still work with 1.30.

**Comment by kazuf3** [comment]
Thank you, I will try.

`community/rust` is 1.29, btw. I think in this case, do I have to first install `rust-nightly-bin` first?

**Comment by kazuf3** [comment]
ah, `rustup`
I will try it now :)

**Comment by polyzen** [comment]
https://www.archlinux.org/packages/community/x86_64/rust/

**Comment by kazuf3** [comment]
oh, got Rust 1.31 via rustup (and removed repo's rust already). It now works.
